### ISSUE TITLE
Continuous integration tracking issue

### ISSUE THREAD

**Issue by BD103** [Phoenix-Wing/Reservoir#10]
Setting up Github actions to check PRs, commits on main, and automate releases would be super nice. I worry it may not be worth the effort, but it should at least be considered.

- [ ] Lint, typecheck, and build every commit and PR
  - [x] #25
  - [ ] #51
- [ ] Integrate [Nuxt testing](https://nuxt.com/docs/getting-started/testing) with CI
- [ ] Build nightly release artifacts
- [ ] Automate building release artifact

**Comment by BD103** [comment]
Closing for now. I had some issues getting EdgeDB installed in a CI environment. Specifically, generating queries requires access to the initialized and migrated database. Query generation is a postinstall step, so you can't really skip it. I may revisit this in the future if I think the project needs it.
