### ISSUE TITLE
Economy v2

### ISSUE THREAD

**Issue by BD103** [Phoenix-Wing/Reservoir#32]
Economy v2 will be introduced with Phoenix Wing Season 2.

# Phase 1

- [x] #30
- [x] Country sizes (small, medium, large) for foodstuffs and military size (851584a)
- [x] Independent resource production (builtin with upkeep and income)

# Phase 2

- [x] #42
- [x] Display country sizes on page (4ad6dfbc09590cc49863b4cf8a110baee8ddf7b8)

# Phase 3

- [x] #36
